{% set name = "napari-bil-data-viewer" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/napari-bil-data-viewer-{{ version }}.tar.gz
  sha256: 12bd24b1a2e0452f881f664c4a3c6e4c09ebf59e99f7f2006fa8673d1c099485

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools-scm
  run:
    - aiohttp
    - beautifulsoup4
    - dask-core
    - fsspec
    - imagecodecs
    - napari
    - napari-plugin-engine >=0.1.4
    - python >={{ python_min }}
    - requests
    - scikit-image

test:
  imports:
    - napari_bil_data_viewer
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/brain-image-library/napari-bil-data-viewer
  summary: Napari plugin for viewing Brain Image Library datasets
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
